### ISSUE TITLE
Programming Language for the scripts

### ISSUE THREAD

**Issue by JonM313** [TestConnect24/Channels#1]
What programming language should we use for the scripts?

**Comment by dhtdht020** [comment]
That's not the place.

**Comment by JonM313** [comment]
Yes it is cuz this is one place they will be lol

**Comment by JonM313** [comment]
Pointless

**Comment by caution3** [comment]
CornierKhan1 here,
If you are looking at languages that are used on web side, you could use what RC24/DC24 uses, which is Go Language. (Used for Mail at this time.) An alternative language that can also be used is Python.

**Comment by dhtdht020** [comment]
use go
mkwii ripper will probs choose html or something so it's better to announce it too

**Comment by Fun4TubeGr** [comment]
RiiConnect24 uses python 2 and wil be using python 3 to make channel works better

**Comment by dhtdht020** [comment]
RC24 uses go for mail @Fun4TubeGr

**Comment by caution3** [comment]
@Fun4TubeGr It doesn't use Python anymore, it has switched to Go after DC24 and RC24 merged and secured mail. 😄

**Comment by Fun4TubeGr** [comment]
Yes wil be using go with htyps for wii mail and for channel file maker python 3

**Comment by MarkTheFreak** [comment]
But, how would HTTPS work for Wii Mail? Why can't you just use Golang like RC24/DC24 does or even just PHP (Which is what RC24 used to use)?
